learning_templates/basicapp/urls.py
from django.conf.urls import url
from basicapp import views

#TEMPLATE TAGGING
app_name = 'basicapp'
urlpatterns = [
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^other/$',views.other,name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basicapp import views
urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^basicapp/',include('basicapp.urls'))
]

learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    #FOR CUSTOM FILTERS
    context_dict = {'text':'hello world','number':1000}
    return render(request,'basicapp/index.html',context_dict)#con dict onnly for filters

def other(request):
    return render(request,'basicapp/other.html')

def relative(request):
    return render(request,'basicapp/rel_url_temp.html')

learning_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <nav  class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'basicapp:other' %}">Other</a>
      </div>
    </nav>
    <div class="container">

      {% block body_block %}

      {% endblock %}

    </div>

  </body>
</html>

learning_templates/templates/basicapp/index.html
<!DOCTYPE html>
<!-- <html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body> -->
  {% extends "basicapp/base.html" %}
  {% load my_extras %}
    {% block body_block %}
    <h1>WELCOME TO INDEX!</h1>
    <h1>This is index.html showing.</h1>
    <h2>{{ text|upper }}</h2>
    <h2>{{ text|cut1:'hello' }}</h2>
    <h2>{{ number|add:'99' }}</h2>
    {% endblock %}
  <!-- </body>
</html> -->

learning_templates/templates/basicapp/other.html
<!DOCTYPE html>
<!-- <html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body> -->
  {% extends "basicapp/base.html" %}
    {% block body_block %}
    <h1>WELCOME TO OTHER!</h1>
    <h2>This is an example  of template inheritance</h2>
    {% endblock %}
  <!-- </body>
</html> -->

learning_templates/templates/basicapp/rel_url_temp.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES!</h1>
    <a href="{% url 'basicapp:other' %}">THE OTHER PAGE</a><br>
    <!-- #FOR ADMIN PAGE -->
    <a href="{% url 'admin:index' %}">ADMIN PAGE</a><br>
    <a href="{% url 'index' %}">INDEX PAGE</a>
  </body>
</html>